fixed incorrect regex for handling the hostnames
sap-linuxlab/ansible.playbooks_for_sap pull request #36
Opened 2024-08-06 08:55 UTC by RishabhKodes

Removed hardcoded reject for all hostnames containing '0'

Replaced with regex search checking for "ending with 0" instead.
```
# Before
reject('search', '0')

# After
reject('regex', '0$')
```

2024-08-08 08:39 UTC, Wabri requested changes

2024-08-08 08:39 UTC, Wabri commented on deploy_scenarios/sap_bw4hana_standard_scaleout/ansible_playbook.yml
> +            {%- for host in (groups['hana_primary'] | reject('search', '0$') | list)[:-1] -%}
```suggestion
            {%- for host in (groups['hana_primary'] | reject('regex', '0$') | list)[:-1] -%}
```

2024-08-08 08:39 UTC, Wabri commented on deploy_scenarios/sap_bw4hana_standard_scaleout/ansible_playbook.yml
> +            {%- for host in (groups['hana_primary'] | reject('search', '0$') | list) -%}
```suggestion
            {%- for host in (groups['hana_primary'] | reject('regex', '0$') | list) -%}
```

2024-08-08 08:39 UTC, Wabri commented on deploy_scenarios/sap_hana_scaleout/ansible_playbook.yml
> +            {%- for host in (groups['hana_primary'] | reject('search', '0$') | list)[:-1] -%}
```suggestion
            {%- for host in (groups['hana_primary'] | reject('regex', '0$') | list)[:-1] -%}
```

2024-08-08 08:39 UTC, Wabri commented on deploy_scenarios/sap_hana_scaleout/ansible_playbook.yml
> +            {%- for host in (groups['hana_primary'] | reject('search', '0$') | list) -%}
```suggestion
            {%- for host in (groups['hana_primary'] | reject('regex', '0$') | list) -%}
```

2024-08-09 09:54 UTC, Wabri approved these changes

2024-12-01 10:55 UTC, sean-freeman commented
Didn't see this PR prior, sorry! Thank you for the effort. Resolved in PR #39

2024-12-01 10:55 UTC, closed without merging